import Head from 'next/head'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { useTranslation } from 'next-i18next'
import { useSession } from "next-auth/react"
import { Text } from '@nextui-org/react';

import Layout from '../../components/layout'

export default function ComponentHandler({ locale }) {
  const { t } = useTranslation('common');
  const { data: session, status: sessionStatus } = useSession();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout locale={locale} restricted={true}>
          <Text h1>{t('Dashboard Page')}</Text>
          <Text >{t('test')}</Text>
      </Layout>
    </>
  )
}

export async function getStaticProps({ locale }) {
  const translations = (await serverSideTranslations(locale, ['common']))

  return {
    props: { ...translations, locale },
  }
}
