import { useState } from 'react';
import Head from 'next/head'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { useSession } from "next-auth/react"
import { useTranslation } from 'next-i18next'
import { Card, Grid, Input, Text, Button, Loading } from '@nextui-org/react';
import { FaChevronRight } from "react-icons/fa";

import Layout from '../../components/layout'

export default function ComponentHandler({ locale }) {
  const { t } = useTranslation('common');
  const { data: session, status: sessionStatus } = useSession();

  const [error, setError] = useState('');
  const [processing, setProcessing] = useState(false);

  const [fullName, setFullName] = useState(session ? session.user.name : '');
  const [username, setUsername] = useState(session ? session.user.email : '');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');


  const handleForm = () => {
    setProcessing(true);
    setPassword('');
    setConfirmPassword('');

    if ((password || confirmPassword) && password !== confirmPassword) {
      setProcessing(false);
      setError('Password confirmation do not match password!')
    }

    // @todo: handle user update.
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout locale={locale} restricted={true} >
        <Grid.Container gap={4} justify="center">
          <Grid xs={12} md={6} >
            <Card>

              <Card.Header>
                <Grid.Container css={{ pl: "$6" }}>
                  <Grid xs={12} justify="center">
                    <Text h1 size={60} css={{ textGradient: "45deg, $yellow600 -20%, $red600 100%" }} weight="bold">{t('Porfile')}</Text>
                  </Grid>
                </Grid.Container>
              </Card.Header>

              <Card.Body>
                <Grid xs={12}>
                  <Input
                    name='fullName'
                    size="md"
                    fullWidth={true}
                    type="text"
                    clearable
                    underlined
                    labelPlaceholder="Full Name"
                    // contentLeft={<FaUserCircle />}
                    initialValue={fullName}
                    value={fullName}
                    onChange={(event) => setFullName(event.target.value)}
                    disabled={processing}
                  />
                </Grid>
                <Grid xs={12}>
                  <Input
                    name='username'
                    size="md"
                    fullWidth={true}
                    type="email"
                    clearable
                    underlined
                    labelPlaceholder="Username"
                    // contentLeft={<FaUserCircle />}
                    initialValue={username}
                    value={username}
                    onChange={(event) => setUsername(event.target.value)}
                    disabled={processing}
                  />
                </Grid>
                <Grid xs={12}>
                  <Input.Password
                    name='password'
                    size="md"
                    fullWidth={true}
                    underlined
                    labelPlaceholder="Password"
                    // contentLeft={<FaLock />}
                    initialValue={password}
                    value={password}
                    onChange={(event) => setPassword(event.target.value)}
                    disabled={processing}
                  />
                </Grid>
                <Grid xs={12}>
                  <Input.Password
                    name='confirmPassword'
                    size="md"
                    fullWidth={true}
                    underlined
                    labelPlaceholder="Confirm Password"
                    // contentLeft={<FaLock />}
                    initialValue={password}
                    value={confirmPassword}
                    onChange={(event) => setConfirmPassword(event.target.value)}
                    disabled={processing}
                  />
                </Grid>

                {error && <Grid xs={12}>
                  <Text h6 color="error">{error}</Text>
                </Grid>}
              </Card.Body>

              <Card.Footer>
                <Grid xs={12} justify="right">
                  <Button auto flat onClick={handleForm} disabled={processing}>
                    {processing ? <Loading type="points" color="currentColor" size="sm" /> : <>{t('Save')} <FaChevronRight /></>}
                  </Button>
                </Grid>
              </Card.Footer>

            </Card>
          </Grid>
        </Grid.Container>
      </Layout>
    </>
  )
}

export async function getStaticProps({ locale }) {
  const translations = (await serverSideTranslations(locale, ['common']))

  return {
    props: { ...translations, locale },
  }
}
