import Head from 'next/head'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { useTranslation } from 'next-i18next'
import { getProviders } from "next-auth/react"

import Layout from '../components/layout'
import styles from '../styles/Home.module.css'

export default function ComponentHandler({ locale, providers }) {
  const { t } = useTranslation('common');

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout locale={locale} providers={providers}>
        <main className={styles.main}>
          <h1 className={styles.title}>
            {`${t('welcome')} ${process.env.NEXT_PUBLIC_APP_NAME}`}
          </h1>

          <p>{t('test')}</p>

          <p className={styles.description}>
            Get started by editing{' '}
            <code className={styles.code}>pages/index.js</code>
          </p>

          <div className={styles.grid}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>

            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>

            <a
              href="https://github.com/vercel/next.js/tree/canary/examples"
              className={styles.card}
            >
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
              className={styles.card}
            >
              <h2>Deploy &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </div>
        </main>
      </Layout>
    </>
  )
}

export async function getStaticProps({ locale }) {
  const providers = await getProviders() // @todo: review if necessary here.
  const translations = (await serverSideTranslations(locale, ['common']))

  return {
    props: { ...translations, providers, locale },
  }
}
